version: '3'
services:
  zabbix-mysql-server:
    container_name: zabbix-mysql-server
    image: mysql
    network_mode: "bridge"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
    volumes:
      - /opt/dbdata:/etc/dbdata
  zabbix-server-mysql:
    container_name: zabbix-server-mysql
    image: zabbix/zabbix-server-mysql:latest 
    network_mode: "bridge"
    restart: always
    ports:
      - "10051:10051"
    links:
      - zabbix-mysql-server:mysql
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=123456
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /opt/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /opt/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql
    network_mode: "bridge"
    restart: always
    depends_on:
      - zabbix-mysql-server
      - zabbix-server-mysql
    ports:
      - "8000:80"
      - "8443:443"
    links:
      - zabbix-mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=123456
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    volumes: 
      - /etc/localtime:/etc/localtime:ro 
      - /opt/nginx:/opt/nginx
  zabbix-agent-a:
    container_name: zabbix-agent-a
    image: zabbix/zabbix-agent:latest
    network_mode: "bridge"
    restart: always
    links:
      - zabbix-server-mysql:zabbix-server
      - zabbix-web-nginx-mysql:zabbix-web
    depends_on:
      - zabbix-server-mysql
      - zabbix-web-nginx-mysql
    volumes:
      - /opt/zabbix-agent:/data/zabbix-agent
    environment:
      - ZBX_HOSTNAME=zabbix-agent-a
      - ZBX_SERVER_HOST=zabbix-server
  zabbix-agent-b:
    container_name: zabbix-agent-b
    image: zabbix/zabbix-agent:latest
    network_mode: "bridge"
    restart: always
    links:
      - zabbix-server-mysql:zabbix-server
      - zabbix-web-nginx-mysql:zabbix-web
    depends_on:
      - zabbix-server-mysql
      - zabbix-web-nginx-mysql
    volumes:
      - /opt/zabbix-agent-b:/data/zabbix-agent-b
    environment:
      - ZBX_HOSTNAME=zabbix-agent-b
      - ZBX_SERVER_HOST=zabbix-server