version: '2'
services:
  activemq:
    hostname: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
      - ./data/:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST="/"
      #- RABBITMQ_DEFAULT_USER="admin"
      #- RABBITMQ_DEFAULT_PASS="admin"