version: '3.1'

services:
  db:
    image: mongo
    container_name: pmongo
    restart: always
    env_file:
      - ./base.config
    volumes:
      #- "./data/db:/data/db"
      #- "./data/log:/data/log"
      - "${db}:/data/db"
      - "${log}:/data/log"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 654321
    command: --dbpath /data/db --logpath /data/log/dblog.log --auth

